services:
  mongodb:
    image: mongo:8.2
    
    container_name: mongodb
    
    ports:
      - "27010:27017"
    
    volumes:
      - "rag_mongo_db:/data/db"
    
    networks:
      - backend
    
    restart: always

volumes:
  rag_mongo_db:


networks:
  backend:

