services:
  # FastAPI Application
  fastapi:
    build:
      context: ..
      dockerfile: docker/legal-rag-app/Dockerfile 
    container_name: fastapi
    ports:
      - "5000:8000"
    networks:
      - backend
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy  

    env_file:
      - "./env/.env.app"

  # Nginx Service (pronounced engine-x)
  # which is: A high-performance "web server", "reverse proxy", and "load balancer".
  # Browser → Nginx (port 80)
  #           ↓
  #       FastAPI (port 8000)
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend
    restart: always

  # MongoDB 
  mongodb:
    image: mongo:8.2
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - "rag_mongo_db:/data/db"
    env_file:
      - "./env/.env.mongodb"
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # # Prometheus Monitoring
  # prometheus:
  #   image: prom/prometheus:v3.3.0
  #   container_name: prometheus
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - prometheus_data:/prometheus
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - backend
  #   restart: always
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--web.console.libraries=/etc/prometheus/console_libraries'
  #     - '--web.console.templates=/etc/prometheus/consoles'
  #     - '--web.enable-lifecycle'

  # # Grafana Dashboard
  # grafana:
  #   image: grafana/grafana:11.6.0-ubuntu
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   env_file:
  #     - ./env/.env.grafana
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - backend
  #   restart: always


  # # Node Exporter for system metrics
  # node-exporter:
  #   image: prom/node-exporter:v1.9.1
  #   container_name: node-exporter
  #   ports:
  #     - "9100:9100"
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   networks:
  #     - backend
  #   restart: always



  # # MongoDB-Exporter for DB metrics
  # mongodb-exporter:
  #   image: percona/mongodb_exporter:0.48.0
  #   container_name: mongodb-exporter
  #   ports:
  #     - "9216:9216"
  #   env_file:
  #     - "./env/.env.mongodb-exporter"
  #   depends_on:
  #     - mongodb
    
  #   networks:
  #     - backend
  #   restart: always
    

networks:
  backend:
    driver: bridge

volumes:
  fastapi_data:
  rag_mongo_db:
  # prometheus_data:
  # grafana_data: